//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDetails_veg
    {
        public int id { get; set; }
        public string Food_name { get; set; }
        public string Ingredients { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
