//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.orderHistories = new HashSet<orderHistory>();
        }
    
        public int uid { get; set; }
        public string uName { get; set; }
        public string uPassword { get; set; }
    
        public virtual ICollection<orderHistory> orderHistories { get; set; }
    }
}
