//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Page
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sb09DBcontext : DbContext
    {
        public sb09DBcontext()
            : base("name=sb09DBcontext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login> Logins { get; set; }
        public DbSet<FoodDetails_nonveg> FoodDetails_nonveg { get; set; }
        public DbSet<FoodDetails_veg> FoodDetails_veg { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<orderHistory> orderHistories { get; set; }
    
        public virtual int usp_orderlist(Nullable<int> userid, Nullable<int> totalprice)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var totalpriceParameter = totalprice.HasValue ?
                new ObjectParameter("totalprice", totalprice) :
                new ObjectParameter("totalprice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_orderlist", useridParameter, totalpriceParameter);
        }
    }
}
