//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Page
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderHistory
    {
        public int orderid { get; set; }
        public Nullable<int> totalprice { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
